### ISSUE TITLE
Render this new book skeleton online

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#1]
I've put together a bare-bones outline of a "Foundations" content collection as discussed [here](https://github.com/ProjectPythia/projectpythia.github.io/discussions/41) and at the IWG meeting earlier today.

It renders nicely with Jupyter Book on my local machine. I need some help to get it rendered publicly online somewhere. I think it would be great to host this at <https://foundations.projectpythia.org>, but we can debate the best location.

Ping @kmpaul @andersy005 and any other infrastructure-oriented folks?

**Comment by brian-rose** [comment]
Ok I added a github action to build and deploy here: https://projectpythia.org/pythia-foundations/

That's probably good enough for now, just so folks can take a look and give feedback. We can discuss later what we want the permanent URL to be.

**Comment by kmpaul** [comment]
Nice, @brian-rose!

**Comment by brian-rose** [comment]
I'll close this now. We can discuss names and URLs over in https://github.com/ProjectPythia/projectpythia.github.io/discussions/52.
