### ISSUE TITLE
Clear out "user experience" identifier

### ISSUE THREAD

**Issue by dcamron** [ProjectPythia/pythia-foundations#101]
Currently in our template and notebooks we identify a vague "experience level" in the prerequisite information. Currently it's best to just take these out of everything and not have to evaluate these ourselves or expect users to self-evaluate. We should look forward to some sort of self-evaluation and better guidance on choosing a path through our content.

**Comment by brian-rose** [comment]
I think this is done with the merge of #106. Close this?
