### ISSUE TITLE
Dask Section

### ISSUE THREAD

**Issue by mgrover1** [ProjectPythia/pythia-foundations#108]
@andersy005 put together some nice content on dask within the xarray + dask python tutorials - could this fall within the foundations content as well? I can put together a first pass and we can iterate...

**Comment by brian-rose** [comment]
Discussed at the EWG meeting 2/17/2022. The consensus is that Dask is too complicated to really fit in Foundations. There's a clear need for good tutorial material on xarray + dask. A perfect topic for a future Pythia Cookbook.

Now mentioned over at https://github.com/ProjectPythia/pythia-cookbook/issues/1
