### ISSUE TITLE
Revert Google Analytics Workaround Once pydata_sphinx_theme Fix Released 

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/pythia-foundations#128]
We now have Google Analytics working for our Foundations Book with the help of PR #123. 

Our PR was just a workaround until [pydata/pydata-sphinx-theme#439](https://github.com/pydata/pydata-sphinx-theme/pull/439)gets merged and released. So, once it is done, our PR #123 should better be reverted.

**Comment by brian-rose** [comment]
Just noting here that https://github.com/pydata/pydata-sphinx-theme/pull/439 was apparently merged recently, so we can circle back to this whenever the next release of pydata-sphinx-theme happens (currently at v0.6.3)

**Comment by erogluorhan** [comment]
Yes, I am keeping my eyes on their release, too. Thanks for reminding!
