### ISSUE TITLE
Linkify too aggressive

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/pythia-foundations#130]
In my most recent PR #129 JupyterBook kept trying to render a file path as an html link. I think this is because we have linkify set up to automatically detect links, and it is too aggressive. I'm not sure if we want to disable linkify or perhaps find a way to tone it down.

https://github.com/ProjectPythia/pythia-foundations/blob/000661ff92f544e95efdaebe88c2c10b1f3c734b/_config.yml#L28

**Comment by dcamron** [comment]
`linkify-it` does appear to include `.py` domains by default. Looks like myst/markdown-it-py don't provide for any config to linkify-it-py, so it doesn't look particularly straightforward/not-hacky for us to relax it ourselves?

I don't see us often typing "xxxx.py" without it being `code`, but also I don't think we're necessarily _relying_ on `linkify` either. I guess we make sure people are using `code` thoroughly, and/or we disable `linkify`.

Tangentially related is that we _can_ pretty easily add ignores to the linkcheck builder through sphinx options in `_config.yml` if we want, which I tried while checking this out and does work fine (doesn't address the root issue here though.)

**Comment by clyne** [comment]
BR, DC: we should not use linkify-it at all. Let's get rid of it. @kmpaul if you are ok with this can you make the change?

**Comment by kmpaul** [comment]
It might be nice to know what links fail without the checks failing.

**Comment by jukent** [comment]
> It might be nice to know what links fail without the checks failing.

That would be nice! I do think that is separate from `linkify` and has more to do with `link-checker` though (perhaps a soft check with a warning instead of a failure).

Currently `linkify` automatically looks for links, which I'm not sure we need because all links should be intentionally by the author.

One work around we discussed in the IWG is that we should always style paths in codeblocks, so `.py` files aren't seen as potential links. 

It seemed the consensus was to do both: have this consistent style - and remove any plugins that we don't find helpful.

**Comment by brian-rose** [comment]
+1 for removing plugins that we don't find helpful! Automation is great except when it gets in the way of doing what we want to do. I do not think we have identified any need for `linkify`. 

@kmpaul I do think this is separate from checking links. `linkify` is turning things into link which were not meant to be links, and thus triggering false failures.

**Comment by kmpaul** [comment]
👍 Then I think we should remove `linkify`.
