### ISSUE TITLE
Document PYTHIA_DATASETS_DIR in pythia_datasets package

### ISSUE THREAD

**Issue by ktyle** [ProjectPythia/pythia-foundations#143]
Datasets that are requested from pythia_datasets get stored in the user's .cache directory. Could we do something akin to what Cartopy does in terms of Natural Earth shapefiles, where one could define a different, networked-served directory?

The motivator here is for users who are running scripts or notebooks that use pythia_datasets but who may be logging into a networked-served Linux directory environment (such as in my department at UAlbany). Users' home directories, which is where the .cache directory sits, are limited to a mere 5GB of space.

**Comment by andersy005** [comment]
@ktyle, users can override the default cache location by setting `PYTHIA_DATASETS_DIR` environment variable.

**Comment by ktyle** [comment]
Ok great!!

**Comment by brian-rose** [comment]
Can we get this info into our user guides somewhere?

**Comment by clyne** [comment]
This issue was closed. Did we get an issue opened to document the `PYTHIA_DATASETS_DIR` env. variable?

**Comment by brian-rose** [comment]
No. Suggest just reopening and retitling this issue.

**Comment by brian-rose** [comment]
I opened a PR over on the pythia-datasets repo to address this.

@ktyle Do we need to put any info about this somewhere in the Foundations material?
