### ISSUE TITLE
Broken links in `core/cartopy/cartopy`

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/pythia-foundations#144]
Link-checker is failing PR #131 due to broken links in `core/cartopy` - which was not changed in this PR. So we have some broken links upstream?

```
(    core/cartopy: line   16) broken    https://scitools.org.uk/cartopy/docs/latest/crs/projections.html#cartopy-projections - 404 Client Error: Not Found for url: https://scitools.org.uk/cartopy/docs/latest/crs/projections.html
(core/cartopy/cartopy: line 650005) broken    https://scitools.org.uk/cartopy/docs/latest/crs/projections.html - 404 Client Error: Not Found for url: https://scitools.org.uk/cartopy/docs/latest/crs/projections.html
```

**Comment by jukent** [comment]
This seems like an easy fix if anyone knows where the link is supposed to point.

**Comment by dopplershift** [comment]
The right fix I think is to update to the new link for v0.20: https://scitools.org.uk/cartopy/docs/latest/reference/crs.html#list-of-projections

**Comment by jukent** [comment]
> The right fix I think is to update to the new link for v0.20: https://scitools.org.uk/cartopy/docs/latest/reference/crs.html#list-of-projections

Okay great! I couldn't find the new path that would point to a comparable page.
