### ISSUE TITLE
Previous and next page links are formatted differently in new Xarray notebook

### ISSUE THREAD

**Issue by r-ford** [ProjectPythia/pythia-foundations#157]
In the current preview link in #107, the two links at the bottom of the page are formatted differently for notebook `computation-masking.ipynb`, but not the other new notebook.

**Comment by brian-rose** [comment]
I notice that this problem has disappeared in our latest builds, e.g. https://foundations.projectpythia.org/core/xarray/computation-masking.html#resources-and-references

So I think we can close this?

**Comment by r-ford** [comment]
> 
> 
> I notice that this problem has disappeared in our latest builds, e.g. https://foundations.projectpythia.org/core/xarray/computation-masking.html#resources-and-references
> 
> So I think we can close this?

Sure, it looks good to me.
