### ISSUE TITLE
Conda environment missing dependencies needed for Dask?

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/pythia-foundations#168]
When I try to build #109 locally the Dask components fail with 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/7m/5m80rt_x5b38swj51zdp9qjhyhpj03/T/ipykernel_25891/1519977778.py in <module>
----> 1 import dask
      2 from dask.distributed import Client, LocalCluster

ModuleNotFoundError: No module named 'dask'

**Comment by brian-rose** [comment]
@clyne did this get resolved? Or do you think this issue points to a need to update our guides on how to maintain the `pythia-book-dev` environment?

**Comment by clyne** [comment]
Works now. Thanks! Closing.
