### ISSUE TITLE
Create GitHub issue template to facilitate opening issues

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/pythia-foundations#17]
Not sure if this is the right repo for this issue, but we should explore creating an issue template to facilitate creating new issues. As a starting point, it might be useful to have templates for infrastructure and content (with labels "infrastructure" and "content")

cc @andersy005 , @kmpaul

**Comment by andersy005** [comment]
I just finished setting this up over in https://github.com/ProjectPythia/.github. Every repo under `ProjectPythia` has the following issue templates (templates include some default labels):


![Screen Shot 2021-03-11 at 3 02 10 PM](https://user-images.githubusercontent.com/13301940/110862563-c950bf80-827c-11eb-941f-d23ff6f77b64.png)


To apply labels after the fact (once the issue has been opened), I created a label manifest: https://github.com/ProjectPythia/.github/blob/main/.github/labels.yml that gets synced with individual repositories via a GitHub action: https://github.com/ProjectPythia/.github/blob/main/.github/workflows/labels.yml


![Screen Shot 2021-03-11 at 3 00 33 PM](https://user-images.githubusercontent.com/13301940/110863048-53992380-827d-11eb-8390-474c79e8d1ad.png)

**Comment by andersy005** [comment]
P.S Changes to the label manifest and issue templates must be made in the https://github.com/ProjectPythia/.github for changes to be applied to repositories under the GitHub organization.

**Comment by clyne** [comment]
This looks great @andersy005! Are there currently any label assignments? I opened a test "Content" issue, but didn't see a label applied.

Also, I'm not sure I understand what the "label manifests" does.

**Comment by andersy005** [comment]
> Also, I'm not sure I understand what the "label manifests" does.

I've defined a YAML file: https://github.com/ProjectPythia/.github/blob/main/.github/labels.yml that includes a list of labels. It's this file that I am calling "label manifest". I've added a [GitHub action workflow](https://github.com/ProjectPythia/.github/blob/main/.github/workflows/labels.yml) that syncs these labels in this manifest file to repositories defined [here](https://github.com/ProjectPythia/.github/blob/55c4bbc8bcb3b6bf52e8b65556877f854dc016bc/.github/workflows/labels.yml#L17-L20). 

> Are there currently any label assignments? I opened a test "Content" issue, but didn't see a label applied.

I can confirm that the automatic label assignment isn't working. I will look into it.

**Comment by andersy005** [comment]
@clyne, the automatic labelling of issues when creating issues from a template should now be resolved

**Comment by clyne** [comment]
Templates are enabled on all repos.
