### ISSUE TITLE
Book title: "Pythia Foundations" or "Project Pythia Foundations"?

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#176]
In preparing a video supplement for the Foundations book (#127), @ncorbin-id has identified an ambiguity in the title of the book.

The [landing page](https://foundations.projectpythia.org/landing-page.html) and TOC reference "Project Pythia Foundations".
But the [Preamble](https://foundations.projectpythia.org/preamble/how-to-use.html) (and possibly elsewhere) repeatedly references "Pythia Foundations".

I think we should choose a title and stay consistent! 

FWIW, my vote would be "Pythia Foundations" as the book title.

**Comment by dcamron** [comment]
12/9/21 EWG meeting agreed to settle on "Pythia Foundations" authored by "Project Pythia" per Brian's suggestions here.

@ProjectPythia/outreach ping to make this titling resolution consistent among our efforts as well: Twitter, Medium, portal outreach/contributions etc.

**Comment by brian-rose** [comment]
> 12/9/21 EWG meeting agreed to settle on "Pythia Foundations" authored by "Project Pythia" per Brian's suggestions here.
> 
> @ProjectPythia/outreach ping to make this titling resolution consistent among our efforts as well: Twitter, Medium, portal outreach/contributions etc.

Book and portal are now up to date with consistent titling. Do we need to leave this issue open to address any other media?

**Comment by brian-rose** [comment]
Discussed briefly at EWG meeting 12/23/2021. Ok to close this now.
