### ISSUE TITLE
matplotlib documentation link broken

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#178]
The nightly link checker failed on the link to https://matplotlib.org/stable/contents.html:
https://github.com/ProjectPythia/pythia-foundations/runs/4245572498?check_suite_focus=true#step:6:212

I think this is because the matplotlib website has just been reorganized with new content.

**Comment by dopplershift** [comment]
That new link should be: https://matplotlib.org/stable/

**Comment by brian-rose** [comment]
I'll do a quick fix now.
