### ISSUE TITLE
[Security] Workflow preview-book.yaml is using vulnerable action nwtgck/actions-netlify

### ISSUE THREAD

**Issue by fockboi-lgtm** [ProjectPythia/pythia-foundations#197]
The workflow preview-book.yaml is referencing action nwtgck/actions-netlify using references v1.2. However this reference is missing the commit [223b5b5981680adfe8ec4c9f471620cbbdbfadec](https://github.com/nwtgck/actions-netlify/commits/223b5b5981680adfe8ec4c9f471620cbbdbfadec) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by dopplershift** [comment]
nwtgck/actions@v1.2 has been updated to point to 1.2.3. The referenced commit [appears in the list of commits](https://github.com/nwtgck/actions-netlify/commits/v1.2) now.

Thanks for reporting.
