### ISSUE TITLE
Need a license

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#2]
This repo needs a license! Should it be the same license as the [main portal repo](https://github.com/ProjectPythia/projectpythia.github.io), or something different?

**Comment by clyne** [comment]
I don't see any reason why we wouldn't use the same license for everything we produce.

**Comment by brian-rose** [comment]
For reference, the main portal repo currently uses Apache License 2.0

**Comment by brian-rose** [comment]
Following discussion at today's EWG, I added the Apache License 2.0

We may revisit after @clyne discusses with UCAR legal team, but I'll this for now.

**Comment by clyne** [comment]
I spoke to UCAR legal. The bottom line is that they advise separate licenses for code and other content. Apache 2.0 is fine for code, Creative Commons (CC-BY) is recommended for everything else. I don't think GitHub is really set up for using multiple licenses. We've already made Apache 2.0 the "default" license. We could simply add a note (in the LICENSE file?) that says something like "all software is licensed under Apache 2.0. All other content is licensed under CC-BY"

**Comment by brian-rose** [comment]
I guess the straightforward thing to do is to leave the Apache 2.0 license file in each repo so that github recognizes this as the license for the repo itself. Then we can link to CC-BY in the rendered websites. The README file in each repo can explain the distinction between the software license and the content license.

**Comment by brian-rose** [comment]
Slightly more nuanced version: Apache 2.0 will cover **all** code, including example code snippets that are displayed to users as part of the content.
