### ISSUE TITLE
Add to the overview of the software stack?

### ISSUE THREAD

**Issue by DamienIrving** [ProjectPythia/pythia-foundations#220]
At the moment the [Overview](https://github.com/ProjectPythia/pythia-foundations/blob/main/core/overview.md) section of the "Core Scientific Python Packages" part of the book provides links to more information about numpy, matplotlib, cartopy, pandas, xarray, etc. I was wondering whether it would be worth adding some text to that overview section to explain how the core libraries relate to one another?   

Not all of the content on the PyAOS stack page is relevant, but it gives a sense of what I mean by a description of how the core libraries relate to one another:
https://pyaos.github.io/stack/

If this sounds like a good idea, I'd be happy to submit a PR with some proposed text for others to consider.

**Comment by brian-rose** [comment]
I think it sounds like a great idea and will improve the readability of this section, particularly for new users who are working linearly through the book. I think the current Overview page is more of a placeholder than anything else.

**Comment by DamienIrving** [comment]
Hi, @clyne. This issue was actually resolved in by #265, so already done :smile:

**Comment by clyne** [comment]
Awesome. Thank you!
