### ISSUE TITLE
Quickstart:zero to Python Binder link

### ISSUE THREAD

**Issue by sedv8808** [ProjectPythia/pythia-foundations#226]
In the Quickstart: zero to Python, there is a sentence that mentions to click the Binder link to run the examples.

Could you please add the explanation of the Binder being on the right upper part / make the word Binder be a link? I found it pretty confusing as I was going through the module.

Thank you,

Socorro

**Comment by clyne** [comment]
Thanks for reporting this @sedv8808. Agreed, this is confusing. We will get it addressed in time for the TAC hackathon trainings.

**Comment by brian-rose** [comment]
Thanks for this feedback @sedv8808! 

I just made small fix in #227 that hopefully addresses your concern. You are 100% welcome to take a look at the preview [here](https://620d2b2498bae833d7dda0a6--pythia-foundations.netlify.app/foundations/quickstart.html) and let us know what you think -- either here or over in #227.

**Comment by sedv8808** [comment]
🙌 Thank you! I think this is way clearer.
