### ISSUE TITLE
Link checker CI: forbidden access 

### ISSUE THREAD

**Issue by andersy005** [ProjectPythia/pythia-foundations#260]
`link-checker` CI has been complaining about [broken external links](https://github.com/ProjectPythia/pythia-foundations/runs/5981992819?check_suite_focus=true) from GitHub... the links do exist. it's just that for some reason GitHub servers appear to refuse granting access... 

![Screen Shot 2022-04-11 at 6 26 45 PM](https://user-images.githubusercontent.com/13301940/162854595-e909978d-90ee-4932-8369-a7b89ee3c6c8.png)

i don't know how to fix this :). if someone has a clue, please chime in.

**Comment by brian-rose** [comment]
Weird.

Should we consider disabling the link-checker until a fix is found?

**Comment by kmpaul** [comment]
Or do we just ignore it for now?

**Comment by kmpaul** [comment]
Turns out this issue comes up with any GitHub URL in a "blank" Sphinx document.  I've created an issue on the Sphinx repo to document it:

https://github.com/readthedocs/readthedocs.org/issues/9102

**Comment by kmpaul** [comment]
Temporarily, would could ignore linkchecker on any `docs.github.com` links with the Sphinx option:

`linkcheck_ignore = [r'https://docs.github.com']`

but I don't like this option for very long!

**Comment by brian-rose** [comment]
I think this is the right approach. It's hard to make progress on everything else with all those nasty looking CI failures.

**Comment by kmpaul** [comment]
Ok.  Then I'm going to push that change to @andersy005's #259 PR.
