### ISSUE TITLE
Issue on page /core/xarray/enso-xarray.html

### ISSUE THREAD

**Issue by phil-blain** [ProjectPythia/pythia-foundations#278]
Hi again!

First: great book, I learned a lot of cool things!

I have a small suggestion for the ENSO tutorial:
Here, https://github.com/ProjectPythia/pythia-foundations/blob/fafb7685fbef343b8099d34dbc275a6bf705926c/core/xarray/enso-xarray.ipynb?short_path=a0230fd#L269-L278

we compute the standard deviation of the SST over the Nino 3.4 region, **over the whole time period of the data array**. I think explicitly mentioning that would help, as I was a little confused for a moment by the result being a scalar. In fact I thought maybe the code was wrong and should have been `std_dev = tos_nino34.tos.std(dim=['lat', 'lon'])`.

I think mentioning it outright would help, I think.

**Comment by jukent** [comment]
Thanks for the suggestion @phil-blain ! I will try to get to this this week.
