### ISSUE TITLE
Broken link to Jupyter graphic

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#328]
Our link-checker has been failing for a while now, e.g. https://github.com/ProjectPythia/pythia-foundations/actions/runs/3223393187

The culprit is a graphic at the top of the [Getting Started with Jupyter](https://foundations.projectpythia.org/foundations/getting-started-jupyter.html) page, which links to https://datascience.foundation/backend/web/uploads/blog/Working-with-Python-on-Cloud.png. Seems the datascience.foundation link is inactive.

I don't remember what this graphic actually was. Should we just replace it with a [Jupyter logo](https://jupyter.org/assets/homepage/main-logo.svg)?

**Comment by brian-rose** [comment]
I'll go ahead and assign "high priority" to this because it's causing CI failures.

**Comment by ktyle** [comment]
A trip on the Internet Wayback Machine confirms it's just a [Jupyter logo](https://user-images.githubusercontent.com/1961038/195123693-ccb34976-84c1-49fd-9534-264fa27c3f6c.png).

**Comment by dopplershift** [comment]
Or maybe link this? https://github.com/jupyter/jupyter.github.io/blob/master/assets/logos/rectanglelogo-greytext-orangebody-greymoons.svg

**Comment by dopplershift** [comment]
Or copy it into our repo.
