### ISSUE TITLE
Fix typos throughout foundations book

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/pythia-foundations#337]
There are 48 pages of Foundations. Lily Kailyn went through all the pages and listed typos and corrections in this [excel sheet](https://docs.google.com/spreadsheets/d/1xSnIc25uq9qRQzQtfo0hQVgM14pF33pfwDhabuCZrZw/edit#gid=0) and [Google doc](https://docs.google.com/document/d/1xTnL09TGLl5D5CgYRFx7sy2osgVSVrEjOhx-yLY_GWM/edit?usp=sharing). We need to go through and make these corrections.

**Comment by brian-rose** [comment]
Looks really thorough! This is a great opportunity to polish up our Foundations content.

**Comment by jnmorley** [comment]
I can take pages 10 - 20

**Comment by jukent** [comment]
I'm taking pages 0-10

**Comment by ktyle** [comment]
I will take 21-30

**Comment by jukent** [comment]
Any progress @jnmorley and @ktyle ?

**Comment by jukent** [comment]
@lkailynncar will take on 31-40

**Comment by ktyle** [comment]
@jukent I'm going through pages 21-30 now using Lily's spreadsheet. I do not seem to have access to the Google doc that you linked at the top of this thread.

**Comment by jukent** [comment]
Shared!

**Comment by jnmorley** [comment]
I am a little over half way done. I should have a pull request made by the end of the week.

**Comment by jnmorley** [comment]
@jukent I don't have access to the Google doc linked at the top of this thread any more. Could you share it with me?

**Comment by jukent** [comment]
Since the permissions keep changing on the original doc, I've made a copy here: https://docs.google.com/document/d/1LkP6vzhv2dC9xhMT-Cq_NJ0abSDOPCJQzDAYXcmoqTQ/edit?usp=sharing

**Comment by lkailynncar** [comment]
I am now working on pages 33 and 34.

**Comment by lkailynncar** [comment]
I am now working on pages 35 and 36.

**Comment by lkailynncar** [comment]
I am now working on pages 37 and 38.

**Comment by lkailynncar** [comment]
I am now working on pages 39 and 40. I am planning to finish my own work on page 50 before continuing to pages 41-50.

**Comment by lkailynncar** [comment]
I am finished with pages 31-40. I have also finished my own work on page 50. I have started on pages 41 and 42.

**Comment by lkailynncar** [comment]
I am done with pages 43 and 44, and am now working on pages 45 and 46.

**Comment by lkailynncar** [comment]
I am now working on pages 47 and 48.

**Comment by lkailynncar** [comment]
I am now working on the final pages, 49 and 50.
