### ISSUE TITLE
Host external data files in a separate repository

### ISSUE THREAD

**Issue by andersy005** [ProjectPythia/pythia-foundations#35]
The most recent PRs introduced notebooks that require external data files. I was wondering if we could host external data files in a separate repository so as to avoid blotted git repositories. Hosting these files in an external files would make it easy for repositories to share data files, and we could use [pooch](https://www.fatiando.org/pooch/latest/) to cache these files on first access. 

Relevant PRs:

- https://github.com/ProjectPythia/pythia-foundations/pull/34

- https://github.com/ProjectPythia/pythia-foundations/pull/33

**Comment by dopplershift** [comment]
I think some kind of centralized hosting of the data file makes sense. While we may want to have some caching for build/CI purposes, we should avoid exposing the details of that to the users of the training content. Not only does it raise the cognitive load by introducing additional (unrelated) concepts, but it can also just be a general source of confusion. MetPy's examples have a `get_test_data` helper that pulls data from our static copies on GitHub; we have repeatedly received support requests where users plug their own filenames into the call to `get_test_data` and wonder why it fails.

**Comment by brian-rose** [comment]
I'll be delighted if there's an elegant solution to this problem that avoids confusing the audience. I've struggled the data caching issue with climlab. I'll have to take a look at pooch, that's new to me.

**Comment by clyne** [comment]
It might be worth looking at what the GeoCAT team does for their examples gallery: https://geocat-examples.readthedocs.io/en/latest/ 

CC'ing @erogluorhan for his input

**Comment by erogluorhan** [comment]
We have been using a solution (with the help of our [geocat-datafiles](https://github.com/NCAR/geocat-datafiles) repo) to such a problem for a long while, which is similar to what @andersy005 suggested in the beginning (i.e. we are using `pooch`). You can get insights from README file, but let me detail our workflow a bit more:

- Add data files into relevant category folders (e.g. "netcdf_files", "hdf_files", etc.) in this repo.
- Keep file records in [registry file](https://github.com/NCAR/geocat-datafiles/blob/main/registry.txt)
- This repo has a trivial user API as it provides `geocat.datafiles.get(fname)` function. The repo is distributed as a anaconda package. SO, wherever data files are needed, you install `geocat-datafiles`, and then its use can be exemplified as follows:
```
   import geocat.datafiles as gdf
   datafile = gdf.get("netcdf_files/meccatemp.cdf")
   ds = xr.open_dataset(datafile, decode_times=False)
```

Note: As @clyne suggested, we have been using this thing in several of our repos, mostly in [GeoCAT-examples](https://github.com/NCAR/GeoCAT-examples). Check for example [this script](https://github.com/NCAR/GeoCAT-examples/blob/main/Plots/Contours/NCL_conOncon_5.py).

**What can be the shortcoming of this approach?**

- Individual files in a Github repository are strictly limited to a 100 MB maximum size limit. So, when a bigger file is in hand, it is required to subset that file below 100 MB. It could be only doable if  the variables of interest in that file are just a subset of the entire dataset, and this subsetting adds a little extra work.

Let me know if a similar thing would be useful here.

**Comment by clyne** [comment]
Re GitHub's 100 MB limit: we have an allocation on NCAR's public [DASH](https://www2.cisl.ucar.edu/dash) repository to host data sets used by Pythia. It's a good choice for larger data sets and was part of our Data Management Plan for the proposal.

**Comment by clyne** [comment]
Consensus: move forward with the pooch approach.

**Comment by andersy005** [comment]
As an update: I put together a repo for hosting sample data files. This repo includes a small package for retrieving/caching these data files: https://github.com/ProjectPythia/pythia-datasets. The package can be installed via 

```bash 
python -m pip install git+https://github.com/ProjectPythia/pythia-datasets
```

for the time being.... 




```python
In [1]: from pythia_datasets import DATASETS

In [2]: DATASETS.registry_files
Out[2]: ['jan-17-co-asos.txt.xz', 'NARR_19930313_0000.nc']

In [3]: import pandas as pd

In [4]: filepath = DATASETS.fetch('jan-17-co-asos.txt.xz')

In [5]: filepath
Out[5]: '/Users/abanihi/Library/Caches/pythia-datasets/jan-17-co-asos.txt.xz'

In [6]: df = pd.read_csv(filepath)
```

To update this registry of data files, please open a PR and place the sample data files in the `data` folder.

**Comment by clyne** [comment]
@andersy005 will revisit when possible. This is becoming a priority for Max

**Comment by andersy005** [comment]
I added some documentation [here](https://github.com/ProjectPythia/pythia-datasets#pythia-datasets) on (1) how to add new data files to the repository, (2) how to use these data files. If folks have some additional feedback, please let me know.

**Comment by brian-rose** [comment]
Disregard my previous comment!

**Comment by brian-rose** [comment]
I believe the current [Pandas notebook](https://foundations.projectpythia.org/core/pandas/pandas_fullNotebook.html) needs to be updated to use `pythia-datasets`.
We will also need to add the package to the book `environment.yml`

There may be other notebooks in open PRs that need updating for this.

**Comment by clyne** [comment]
It looks like #36, which will hopefully be approved and merged soon, adds pythia-datasets to environment.yml.

**Comment by brian-rose** [comment]
Also adding it to #33 in a new push coming tonight.

**Comment by brian-rose** [comment]
Now that #72 is merged, we have the infrastructure in place.

Other notebooks just need to do
```
from pythia_datasets import DATASETS
```
and then something like
```
filepath = DATASETS.fetch('enso_data.csv')
```
replacing `enso_data.csv` with the appropriate filename from the data registry.

Example is in the Pandas notebook [here](https://foundations.projectpythia.org/core/pandas/pandas_fullNotebook.html)

**Comment by brian-rose** [comment]
This issue is resolved, closing now.
