### ISSUE TITLE
Updating our installation instructions to use mamba

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#391]
After a good community discussion [on this discourse thread](https://discourse.pangeo.io/t/mamba-mature-enough/3154/10), I think we've settled on advising our users to adopt mamba in some form for their own environment management. 

We need to decide on some details:
- Recommend starting with [mambaforge](https://github.com/conda-forge/miniforge#mambaforge) rather than anaconda?
- Or recommend starting with miniconda (as we currently do) but [updating the solver to use mamba under the hood](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community/)?

Some different views were expressed in the above discourse thread.

Whatever we decide, this chapter of Foundations needs updating:
https://foundations.projectpythia.org/foundations/conda.html

and probably several other bits of Contributor info like this one:
https://projectpythia.org/contributing.html#creating-a-python-environment-that-will-work-with-pythia
and this one:
https://foundations.projectpythia.org/appendix/how-to-contribute.html

It would be great to get this done prior to the summer hackathon. Let's discuss at the next EWG and make an action plan.

**Comment by dopplershift** [comment]
I'm a fan of moving to mambaforge because not only does that get us mamba, but it pre-configures the conda-forge channel as well.

**Comment by brian-rose** [comment]
> I'm a fan of moving to mambaforge because not only does that get us mamba, but it pre-configures the conda-forge channel as well.

I support this. That's how I manage environments on my own machines, and it works beautifully.

We'll just need to make sure our tutorial explains clearly the relationship between mamba and conda, since there are vastly more examples of conda usage out in the wild. 

e.g. in the [metpy installation guide](https://unidata.github.io/MetPy/latest/userguide/installguide.html#installation) the instructions say to do
```
conda install -c conda-forge metpy
```
but the user can replace this with
```
mamba install metpy
```

**Comment by dopplershift** [comment]
When we finally follow up on this, we need to adjust to (probably) use `miniforge`. This gives us the benefit of having the conda-forge channel pre-configured, but there's no need to go to `mambaforge` any more since Mamba is now shipping with both and `mambaforge` is being deprecated. See conda-forge/miniforge#488.

It should also be noted that the Mamba solver should be the default for Conda as well [any day now](https://www.anaconda.com/blog/new-release-anaconda-distribution-2023-07-miniconda-23-5-0-and-more) so even switching instructions to use mamba may no longer be needed.

**Comment by ktyle** [comment]
It looks like libmamba has [finally become the default solver ](https://github.com/conda/conda/blob/main/CHANGELOG.md#2390-2023-09-27)for conda-based installations, e.g. miniconda. However, the most recent installer for miniconda *still uses the classic solver* ... one needs to run "conda update --all" after the initial installation for the solver to change. I can move forward with updating our installation instructions, but will need to revisit yet again once the Miniconda installers finally reflect this change in behavior.

**Comment by brian-rose** [comment]
We discussed this at today's Community Meeting and the consensus seems to be that we should just wait it out, since it appears that miniforge will likely be updated in the not-too-distant future and this will effectively mean that our existing installation instructions will be correct again.

**Comment by ktyle** [comment]
I think we'll need to do something regardless, as our instructions specify **miniconda**, but we should be using **miniforge** (the latter uses the conda-forge channel out-of-the-box).

**Comment by erogluorhan** [comment]
Sounds good; thanks!

**Comment by ktyle** [comment]
https://github.com/ProjectPythia/pythia-foundations/pull/491 is ready for review.

**Comment by dopplershift** [comment]
Closed by #491.
