### ISSUE TITLE
Collect team members' ORCIDs for citation

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#392]
@ProjectPythia/core, over in #388 @jukent is working on creating a citation file for Foundations. We would like to collect [ORCID id numbers](https://orcid.org) for all team members so we can all receive appropriate authorship credit for the book.

Please add a comment or review to #388 with your ORCID. If you don't have one, now is a great time to create one!

**Comment by dopplershift** [comment]
Here's mine: https://orcid.org/0000-0003-2907-038X

**Comment by mgrover1** [comment]
Here is mine: https://orcid.org/0000-0002-0370-8974

**Comment by clyne** [comment]
Here you go: https://orcid.org/0000-0003-2788-9017

**Comment by dcamron** [comment]
[0000-0001-7246-6502](https://orcid.org/0000-0001-7246-6502) - Thanks y'all!

**Comment by brian-rose** [comment]
These have all been merged in #388
