### ISSUE TITLE
Shorter headings and/or grouping of pages under a section

### ISSUE THREAD

**Issue by ahuang11** [ProjectPythia/pythia-foundations#398]
Another suggestion is when there's repeats of prefixes:
<img width="274" alt="image" src="https://github.com/ProjectPythia/pythia-foundations/assets/15331990/a30cf540-ea61-4730-8a4d-33ddf72e932a">

I think they can go under a Getting Started section; relevant code
https://github.com/ProjectPythia/pythia-foundations/blob/1444d12a057257f4f3ec37a0e365de0542366aca/foundations/getting-started-python.md?plain=1#L1

**Comment by erogluorhan** [comment]
Hi @ahuang11 thanks very much for these suggestions! There may even be some configurations to implement such things, e.g. limit the length of headings etc. Please let us know or feel free to create a pull-request if you'd like to contribute to this project to address these suggestions!

**Comment by erogluorhan** [comment]
> Hi @ahuang11 thanks very much for these suggestions! There may even be some configurations to implement such things, e.g. limit the length of headings etc. Please let us know or feel free to create a pull-request if you'd like to contribute to this project to address these suggestions!

Closing this for now but please feel free to reopen it if you need.
