### ISSUE TITLE
expand overview

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/pythia-foundations#4]
Consider adding text to 

https://github.com/ProjectPythia/pythia-foundations/blob/main/foundations/overview.md#overview

emphasizing the need for mastery of the topics here before moving on to advanced topics

**Comment by brian-rose** [comment]
Sounds good. I anticipate an open discussion at the next EWG meeting about the priorities for moving forward with all this content.

**Comment by brian-rose** [comment]
I should have addressed this one in #65. Will do so now.

**Comment by brian-rose** [comment]
Done and closing.
