### ISSUE TITLE
Problems Running content on Binder

### ISSUE THREAD

**Issue by MGomezN** [ProjectPythia/pythia-foundations#402]
Hello!

We are using its content as introductory material to Python for our students. For the newer participants with no previous programming experience, we thought of instructing them to run the lessons in Binder. However, we have noticed that this option is not working right now. Whenever we try to access it, we get different errors.

Searching on the web, we see there are general problems with Binder. They ran out of funding a month ago and reduced capacity https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f

We want to inform you about the issue.

**What happened**:
Having problems running the project Pythia notebooks in Binder

**What you expected to happen**:
"Select “Launch Binder”. After a moment you should be presented with a notebook that you can interact with."

**Comment by brian-rose** [comment]
Hi @MGomezN thanks for this report!

We are actually spinning up a custom Binder service to support Pythia content. It will work like mybinder.org but have much better capacity, though it will require authentication via GitHub. We may be putting out updated instructions about this later this week.

**Comment by MGomezN** [comment]
Dear @brian-rose 

Yesterday I was able to run the code using the "Rocket Ship", but right now is not possible. I tried with Chrome and Firefox closing all windows and clearing the cache. I still got the same error (see image below)
Any advice?
Thanks!
![image](https://github.com/ProjectPythia/pythia-foundations/assets/29388479/0c55ca3c-a9bf-4d55-81f9-36010dcfffbf)

**Comment by brian-rose** [comment]
Currently the binder is restricted to one session per user.

If you visit <https://hub.projectpythia.org> and use your GitHub login credentials, you should see a red button "Stop My Server". That will kill the old session that is still running. You should then find that you can launch a new Binder session.

Thanks for testing this out, it will help us develop some useful instructions for users!

**Comment by MGomezN** [comment]
Thank you, @brian-rose!

I see now the authentification is disabled due to your hackathon :) We will keep an eye on the new changes and are happy to contribute! Our students are going to receive an email today with instructions to use Pythia Foundations Book to learn Python 😄,  so they can be prepared to take the most out of our course (Computational Tools for Climate Science)[https://academy.climatematch.io/about/collaborations]

**Comment by brian-rose** [comment]
@MGomezN great! That's great to know that the Pythia binder may help support the Climatematch academy. We might reach out at some point to gather information about usage which will help in our next round of funding for the binder service.

There may be a few outages here and there with the binder as we make necessary adjustments before, during, and after our hackathon. And we do expect to reenable the authentication requirement after the hackathon. Reach out if you have questions!

Reach out if you have any questions.

**Comment by erogluorhan** [comment]
Hi @MGomezN , I just wanted to check in with you to see if everything on your end is good with Pythia and Binder. If so, I'd like to close this issue; otherwise, we are happy to help!

**Comment by erogluorhan** [comment]
> Hi @MGomezN , I just wanted to check in with you to see if everything on your end is good with Pythia and Binder. If so, I'd like to close this issue; otherwise, we are happy to help!

Closing this now; please feel free to reopen it if you need.
