### ISSUE TITLE
Issue on page /core/data-formats/netcdf-cf.html

### ISSUE THREAD

**Issue by ft236** [ProjectPythia/pythia-foundations#431]
Your issue content here.

SyntaxError:  invalid syntax error for netcdf commands

This error begins here:
netcdf forecast_model {
  attributes:
    :Conventions = "CF-1.7" ;
    :title = "Forecast model run" ;
    :institution = "Unidata" ;
    :source = "WRF-1.5" ;
    :history = "2019-07-16 02:21:52.005718 Python" ;
    :references = "" ;
    :comment = "" ;
}

**Comment by ktyle** [comment]
The above section is Markdown-formatted output from the command that preceded it ... it is not executable Python code.
