### ISSUE TITLE
Calculating Enso with Xarray may need further documentation or instruction to get it to work

### ISSUE THREAD

**Issue by bressler95tops** [ProjectPythia/pythia-foundations#445]
Hello all, thank you for hosting this great project on GitHub.  Today, I wanted to report an issue with your _Enso with Xarray_ example: [here](https://github.com/ProjectPythia/pythia-foundations/blob/main/core/xarray/enso-xarray.ipynb).

It was brought to my attention by someone who was trying to use this example that they were getting this error in the import section:

![image](https://github.com/ProjectPythia/pythia-foundations/assets/137207208/ad87fbed-3100-4183-8067-6a8a64fd999b)

After some research, it would seem that this may be related to Python version 3.12 and onwards having deprecrated pkgutil.ImpImporter.  Solutions seem to indicate a manual installation/upgrade of pip or use of Python 3.11 to fix the issue so maybe having some commentary in there to guide people towards getting it to work would be helpful.

**Comment by ktyle** [comment]
Hi @bressler95tops , thanks for posting this issue! Do you know if the user who experienced this error was running this notebook using our Project Pythia BinderHub? If so, this was resolved at the end of last week (see #441) ... please let us know if the user is still having problems.

**Comment by bressler95tops** [comment]
Thanks @ktyle this user was encountering this a few weeks back and I can see the issue you are referencing was a very short while ago.  And I can see a solution was implemented in the BinderHub and it seems this user is also running from BinderHub as indicated in the OS 101 MOOC they are following this from.  After running the import cell myself, it does seem to work, I will check and see if they are still having an issue.

**Comment by bressler95tops** [comment]
It's safe to say that we can close this issue for now seeing how there is a solution already and having tested it on my end as well using the same method.  If anything else comes up, I can open another issue, thanks for your help.
