### ISSUE TITLE
Need an autobuild for pull requests

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#5]
Before we start opening new PRs to add content to this book, it would be great to get an autobuild triggered for each PR so we can see updates to the rendered book. For the main portal repo, this was accomplished with readthedocs. 

The build is slightly different in this case because it depends on `jupyter-book`. @andersy005 can you advise on how to set this up?

**Comment by brian-rose** [comment]
Is there a way to set this up directly with GitHub Actions / gh-pages? Does it need to go out to a 3rd party service like readthedocs?

**Comment by brian-rose** [comment]
Tagging @kmpaul , the EWG has identified this as a high-priority piece of infrastructure that will accelerate building out the content.

**Comment by andersy005** [comment]
@brian-rose,

> The build is slightly different in this case because it depends on jupyter-book. @andersy005 can you advise on how to set this up?

If you have an account on readthedocs (https://readthedocs.org/), I'd set up a project linked to this repository (this will install a webhook on this repository that triggers builds on readthedocs)


> Is there a way to set this up directly with GitHub Actions / gh-pages? Does it need to go out to a 3rd party service like readthedocs?


Unfortunately, this has to be done from the readthedocs UI: https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by andersy005** [comment]
> The build is slightly different in this case because it depends on jupyter-book. 

You are right. It appears that readthedocs isn't supported yet: https://github.com/executablebooks/jupyter-book/issues/1091

**Comment by brian-rose** [comment]
> You are right. It appears that readthedocs isn't supported yet: [executablebooks/jupyter-book#1091](https://github.com/executablebooks/jupyter-book/issues/1091)

Good find! And my take-away from that discussion is that readthedocs probably *won't* support building JupyterBook sources anytime soon.
