### ISSUE TITLE
Internal vs External Links

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/pythia-foundations#54]
Sometimes on the content pages we have links to other Pythia foundations pages (separate from the nav bars and the "next/previous" buttons on the bottom). We might want to make it more obvious when sending people to other pages we created or away from the site.

One idea is for them to have a set phrase at the beginning, something like, "Jump to: ...".
Or we can force them all to be buttons

Any other ideas?

**Comment by brian-rose** [comment]
To me it makes sense to have all external links open in a new tab by default, while internal links do not.

Unfortunately I don't think that there's any way to control that in Markdown links without putting more raw html into the source files.

**Comment by brian-rose** [comment]
Let's discuss a design strategy at an upcoming meeting.

**Comment by brian-rose** [comment]
Adding infrastructure label to this, as this issue sort of bridges content and infrastructure. Forgot to bring this one up at today's meeting.
