### ISSUE TITLE
Quickstart notebook needs some links for further study

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#64]
In #55 we added a "Zero to Python" quickstart notebook, visible [here](https://foundations.projectpythia.org/foundations/quickstart.html).

Since this *isn't* a comprehensive tutorial on Python syntax, we should really curate a short list of good external resources for Python language learners. We can link to these at the end of the quickstart page.

The page should also link to our own numpy and matplotlib tutorials, once those are in place.

**Comment by brian-rose** [comment]
Here's some low-hanging fruit for a little improvement:
- Use consistent capitalization of "NumPy" and "Matplotlib" in this notebook
- Link to the Foundations pages for NumPy and Matplotlib
- Add a "Resources and references" section (consistent with Foundations template) with links to both Pythia and external resources on basic Python

**Comment by dopplershift** [comment]
The official [tutorial](https://docs.python.org/3/tutorial/index.html) from python.org is how I learned when I started.

**Comment by dcamron** [comment]
Closed in #298
