### ISSUE TITLE
Move How to Contribute to appendix?

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/pythia-foundations#73]
The "how to contribute" information is the up front material visitors come to when accessing the Foundations site. I.e. if you proceed through the book linearly by clicking the next (>>) arrows you quickly get into the gory details of the notebook template, etc. Perhaps we should move this material to the end (appendix?) so that those who want to take a more linear approach get into the more accessible material first (e.g. Getting started with Python).

**Comment by brian-rose** [comment]
Agreed, seems reasonable to me that "How to Contribute" would be an appendix rather than a preamble.

**Comment by clyne** [comment]
Should we make that change?

**Comment by brian-rose** [comment]
That's fine with me, I can put a PR together tonight to reorganize the TOC and update the links to the template.

I'm still plugging away on #33 right now.

**Comment by clyne** [comment]
It's not a priority I don' t think. I 'll see if I can figure it out if I have time, but my JupyterBook kung fu is pretty weak

**Comment by brian-rose** [comment]
Done in #75

**Comment by brian-rose** [comment]
Sorry, getting sleepy. #75 isn't merged yet.
