### ISSUE TITLE
How to Use This Book content needed

### ISSUE THREAD

**Issue by clyne** [ProjectPythia/pythia-foundations#76]
We need to provide guidance on how to download and execute notebooks. We should probably also consider adding a callout in every notebook saying "you can browse the rendered notebook, but if you want to interact with the book contents you'll need to download and execute. Here's how..."

**Comment by brian-rose** [comment]
The easiest way to interact with the notebooks is by clicking on the Binder link.

Launching the interactive Binder is very slow the first time after a new push to main branch. But after that first launch, mybinder.org stores an image that gets reused, so the user experiences something that feels more plug-and-play.

**Comment by clyne** [comment]
Hah! Didn't even know that we had binder enabled. However, I still feel we may need to give users guidance that points them to Binder for the full experience if we want to reach newbies

**Comment by brian-rose** [comment]
Binder comes for free with JupyterBook :-)

If you look at the quickstart notebook I wrote [here](https://foundations.projectpythia.org/foundations/quickstart.html), it begins with some instructions for how to launch the Binder.

Personally I don't think this should be repeated in every notebook, but instructions DO belong in the "How to use this book" preamble.

**Comment by brian-rose** [comment]
We will author some new material for this.

**Comment by ncorbin-id** [comment]
This might be a nice place for a video demonstration in conjunction with written steps. I make a lot of these types of videos and could knock one out pretty quick, provided someone gave me the steps. Happy to contribute if folks are interested.

**Comment by clyne** [comment]
That is an an awesome idea, @ncorbin-id . Maybe we can team up on this. I could get a draft of the written documentation going, and once it passes review we could do the video. Sound good?

**Comment by ncorbin-id** [comment]
Sounds good @clyne. Keep me posted!
