### ISSUE TITLE
Documentation for the book preview workflow

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#85]
I have a specific request for @andersy005: could you possibly write up some instructions on how you set up the book preview for PRs on Netlify?

I think this would be a valuable service for many other Jupyter Book projects. 

Full disclosure, this partly a self-serving request because I'm trying to set up a similar workflow for my Climate Laboratory repo, e.g. https://github.com/brian-rose/ClimateLaboratoryBook/pull/26
And I wasn't able to figure out how to get things working on netlify.

**Comment by andersy005** [comment]
@brian-rose, 

> could you possibly write up some instructions on how you set up the book preview for PRs on Netlify?

Definitely. I will ping you once I have these instructions ready (around this Thursday or Friday)

**Comment by andersy005** [comment]
I plan on working on this once #136 is merged
