### ISSUE TITLE
Timing estimates

### ISSUE THREAD

**Issue by dcamron** [ProjectPythia/pythia-foundations#87]
Suggestion from @ncorbin-id:
Make our template and notebook time estimates some multiple of 5 minutes where short/normal-length sections of content take about 5 minutes to process and longer sections take 10. Even if these are totally off,  the "short/medium/long" isn't particularly helpful as-is. We can eventually target learners to evaluate our timing estimates if needed.

**Comment by brian-rose** [comment]
More suggestions from @ncorbin-id:
Do a rough cut based on number of sections / subsections. Adapt based on real world usage.

**Comment by brian-rose** [comment]
We may be able to gather usage statistics from @ktyle class this fall.

**Comment by dcamron** [comment]
> More suggestions from @ncorbin-id:
> Do a rough cut based on number of sections / subsections. Adapt based on real world usage.

Suggestion: 5 mins per subsection, 10 if longer; add these up for a total. Safer to round up and overestimate

**Comment by brian-rose** [comment]
I think we can close this since #106 got merged.
