### ISSUE TITLE
NumPy Basics - array indexing visualization

### ISSUE THREAD

**Issue by r-ford** [ProjectPythia/pythia-foundations#94]
I think the NumPy Basics notebook would benefit from having some sort of visualization of array indexing and slicing, similar to the tutorials [here](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/) and [here](https://fgnt.github.io/python_crashkurs_doc/include/numpy.html).

**Comment by brian-rose** [comment]
Let's add both the tutorials you linked above to the resource gallery.

**Comment by brian-rose** [comment]
The image [here](https://fgnt.github.io/python_crashkurs_doc/include/numpy.html#what-is-numpy) appears to be copied (probably without permission) from this book:
https://www.oreilly.com/library/view/elegant-scipy/9781491922927/ch01.html
"Elegant Scipy" published by O'Reily.
