### ISSUE TITLE
Intro to Jupyter content

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#97]
Merge or adapt material from Jupyter Meets the Earth project.

**Comment by kmpaul** [comment]
Xdev Tutorial material is here:

https://drive.google.com/drive/folders/1zNnBpagQi872f7bo-pkW4WhZKnn97NkW?usp=sharing

**Comment by clyne** [comment]
[Here](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007007) is a reference to consider including.

**Comment by kmpaul** [comment]
Fernando Perez's overview of the Jupyter ecosystem is here:

https://docs.google.com/presentation/d/1NcBVBBgHjXM-1rpBzlkqwlUlvcr_RpZOh5yMyDJOwRU/edit#slide=id.gdc01f99340_0_0

and an updated version is here:

https://docs.google.com/presentation/d/16Zo7A5z4HQkWz92Ph6e8gEhH3k6ITZKhzIRJyzXuqaY/edit#slide=id.p1
